#!/bin/bash
docker rm -f radio-service || true
docker build -t radio-capture .
docker run -d -p 8000:8000 -v $(pwd)/data:/data --name radio-service radio-capture
# docker exec radio-service alembic upgrade head